// @ts-check
/**
 * WP-R1 — BULGU REGISTRY (tek gerçeklik kaynağı / source of truth).
 *
 * Bilinen ürün bulguları burada makine-okur biçimde tanımlanır. Spec'lerdeki
 * `test.fail()` guard'ları `knownBugGuard(test, id)` (tests/helpers.js) ile bu
 * kayda bağlanır; `tools/self-check-findings.mjs` çift yönlü tutarlılığı zorlar.
 *
 * KURALLAR
 * - Bilinmeyen alan `null` / `[]` bırakılır; ASLA uydurulmaz.
 * - `rootCause` yalnız kaynak-kod veya geliştirici incelemesiyle KANITLANMIŞSA
 *   dolar (confirmed). Otomatik/forensik çıktı yalnız `possibleCauses` /
 *   `technicalEvidence` / (WP-R3) `rootCauseCandidate` üretebilir.
 * - `evidence[].piiReviewed` yalnız gerçekten PII taramasından geçmiş kanıt için
 *   `true` olur; legacy ekran görüntüleri varsayılan `false` (rapora gömülmez).
 *
 * ALANLAR
 *   id            benzersiz kimlik (spec'te knownBugGuard(test, id) ile eşleşir)
 *   title         kısa başlık
 *   area          ürün alanı (voice|campaigns|inbox|settings|channels|analytics|
 *                 ai|reports|supervisor|contacts|navigation)
 *   route         birincil rota veya yüzey
 *   severity      'critical' | 'high' | 'medium' | 'low'
 *   status        'open' | 'fixed-candidate' | 'closed'
 *   guard         'knownBugGuard' | 'fixme' | 'permanent'
 *                   knownBugGuard: test `knownBugGuard(test,id)` ile expected-fail
 *                   fixme:         test.fixme ile bekletiliyor (ör. data-testid yok)
 *                   permanent:     bulgu düzelmiş; test.fail'siz kalıcı regresyon guard'ı
 *   opened        açılış tarihi (ISO) | null
 *   lastVerified  son canlı doğrulama (ISO) | null
 *   expiry        gözden geçirme/son kullanma (ISO) | null
 *   repro         yeniden üretme adımları (kısa) | []
 *   expected      beklenen davranış | null
 *   actual        gözlenen davranış | null
 *   technicalEvidence  forensik teknik kanıt (WP-R3 doldurur) | []
 *   possibleCauses     olası nedenler (kaynakta belgelenen) | []
 *   rootCauseCandidate forensik kök-neden adayı (WP-R3) | null
 *   rootCause          KANITLANMIŞ kök-neden | null
 *   suggestedFixes     önerilen düzeltmeler | []
 *   evidence           [{ path, source, piiReviewed }]
 *   test               { file, title }  guard testinin yeri
 *   owner              sorumlu | null
 *   issueRef           harici ticket referansı (ileride Jira/Zoho/Qntrl) | null
 */

/** @typedef {'critical'|'high'|'medium'|'low'} Severity */
/** @typedef {'open'|'fixed-candidate'|'closed'} Status */
/** @typedef {'knownBugGuard'|'fixme'|'permanent'} Guard */

export const SEVERITIES = Object.freeze(['critical', 'high', 'medium', 'low']);
export const STATUSES = Object.freeze(['open', 'fixed-candidate', 'closed']);
export const GUARDS = Object.freeze(['knownBugGuard', 'fixme', 'permanent']);

export const KNOWN_BUGS = Object.freeze([
  {
    id: 'B1',
    title: 'Ham i18n anahtarları görünüyor (regülasyon sayfası)',
    area: 'voice',
    route: '/voice/regulatory',
    severity: 'critical',
    status: 'open',
    guard: 'knownBugGuard',
    opened: null,
    lastVerified: '2026-07-28',
    expiry: null,
    repro: ['/voice/regulatory aç', 'KYC içeriği yüklensin', 'sayfa metnini oku'],
    expected: 'Çevrilmiş etiketler görünür (ör. "Start KYC")',
    actual: '9 ham i18n anahtarı görünüyor (voiceRegulatory.title, .startKyc, …)',
    technicalEvidence: [],
    possibleCauses: [],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: [],
    evidence: [],
    test: { file: 'tests/known-bugs.authed.spec.js', title: 'B1 · /voice/regulatory · ham i18n anahtarları görünmemeli' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'B2',
    title: 'Kampanya ilerleme yüzdesi 100ü aşıyor',
    area: 'campaigns',
    route: '/campaigns',
    severity: 'high',
    status: 'open',
    guard: 'knownBugGuard',
    opened: null,
    lastVerified: '2026-07-28',
    expiry: null,
    repro: ['/campaigns aç', 'kampanya kartlarının yüzde metnini oku'],
    expected: 'Tüm ilerleme yüzdeleri ≤ 100',
    actual: '%200 gözlendi',
    technicalEvidence: [],
    possibleCauses: [],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: [],
    evidence: [],
    test: { file: 'tests/known-bugs.authed.spec.js', title: 'B2 · /campaigns · ilerleme yüzdesi 100ü aşmamalı' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'B3',
    title: 'Ham i18n anahtarı inbox.noMessagesYet görünüyor',
    area: 'inbox',
    route: '/inbox',
    severity: 'high',
    status: 'open',
    guard: 'knownBugGuard',
    opened: null,
    lastVerified: '2026-07-28',
    expiry: null,
    repro: ['/inbox aç', 'Soft Phone başlığı görünsün', 'içerik metnini oku'],
    expected: 'Çevrilmiş boş-durum metni',
    actual: 'Ham anahtar "inbox.noMessagesYet" görünüyor',
    technicalEvidence: [],
    possibleCauses: [],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: [],
    evidence: [],
    test: { file: 'tests/known-bugs.authed.spec.js', title: 'B3 · /inbox · ham i18n anahtarı inbox.noMessagesYet görünmemeli' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'B4',
    title: '"Manage Modules" kök sayfaya (/) düşüyor',
    area: 'settings',
    route: '/settings',
    severity: 'high',
    status: 'open',
    guard: 'knownBugGuard',
    opened: null,
    lastVerified: '2026-07-28',
    expiry: null,
    repro: ['/settings aç', 'Modüller sekmesi', '"Manage Modules" tıkla'],
    expected: 'İlgili modül yönetim sayfası açılır',
    actual: '/settings → (geçici) /settings/billing/marketplace → "/" (kök fallback)',
    technicalEvidence: [],
    possibleCauses: ['Yönlendirme/route fallback zinciri kök route ("/") ile sonuçlanıyor (kaynakta gözlenen akış)'],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: [],
    evidence: [],
    test: { file: 'tests/known-bugs.authed.spec.js', title: 'B4 · /settings · "Manage Modules" kök sayfaya atmamalı' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'B5',
    title: 'Ses kartı yanlışlıkla "Yapılandırılmadı" gösterebiliyor',
    area: 'channels',
    route: '/channels',
    severity: 'medium',
    status: 'open',
    guard: 'fixme',
    opened: null,
    lastVerified: null,
    expiry: null,
    repro: ['/channels aç', 'Voice/Ses kartının durum etiketini oku'],
    expected: 'Ses kartı gerçek durumu gösterir',
    actual: 'Güvenilir test yok; /channels <main> kullanmıyor ve kart için stabil role/testid yok (test.fixme)',
    technicalEvidence: [],
    possibleCauses: [],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: ['Frontend: kart için data-testid (ör. data-testid="channel-card-voice") ekle'],
    evidence: [],
    test: { file: 'tests/known-bugs.authed.spec.js', title: 'B5 · /channels · Ses kartı yanlışlıkla "Yapılandırılmadı" göstermemeli' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'B6',
    title: 'Davet satırları ayırt edilemiyor (placeholder "Invited User")',
    area: 'settings',
    route: '/settings',
    severity: 'medium',
    status: 'open',
    guard: 'knownBugGuard',
    opened: null,
    lastVerified: '2026-07-28',
    expiry: null,
    repro: ['/settings aç', 'Kullanıcılar sekmesi', 'davet satırlarını incele (veri gerektirir)'],
    expected: 'Davet satırları ayırt edilebilir (gerçek e-posta/isim)',
    actual: 'Placeholder "Invited User" satırları ayırt edilemiyor (yalnızca bekleyen davet varsa reproduce olur)',
    technicalEvidence: [],
    possibleCauses: [],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: [],
    evidence: [],
    test: { file: 'tests/known-bugs.authed.spec.js', title: 'B6 · /settings · davet satırları ayırt edilebilir olmalı (placeholder "Invited User" değil)' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'B7',
    title: 'Modüller açıklaması iki kez render ediliyordu',
    area: 'settings',
    route: '/settings',
    severity: 'medium',
    status: 'closed',
    guard: 'permanent',
    opened: null,
    lastVerified: '2026-07-28',
    expiry: null,
    repro: ['/settings aç', 'Modüller sekmesi', 'açıklama paragraflarını say'],
    expected: 'Açıklama tek kez görünür',
    actual: '28 Tem itibarıyla DÜZELMİŞ; kalıcı regresyon guard\'ı olarak tutuluyor',
    technicalEvidence: [],
    possibleCauses: [],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: [],
    evidence: [],
    test: { file: 'tests/known-bugs.authed.spec.js', title: 'B7 · /settings · Modüller açıklaması iki kez render edilmemeli' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'B8',
    title: 'Softphone müsaitlik menüsü görsel açılmıyordu',
    area: 'inbox',
    route: '/inbox',
    severity: 'high',
    status: 'closed',
    guard: 'permanent',
    opened: null,
    lastVerified: '2026-07-28',
    expiry: null,
    repro: ['/inbox aç', 'Softphone müsaitlik tetikleyicisine tıkla', 'menü görünürlüğünü ölç'],
    expected: 'Menü görünür (opacity>0, boyut>0)',
    actual: '28 Tem itibarıyla DÜZELMİŞ; kalıcı regresyon guard\'ı olarak tutuluyor',
    technicalEvidence: [],
    possibleCauses: [],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: [],
    evidence: [],
    test: { file: 'tests/known-bugs.authed.spec.js', title: 'B8 · Softphone · müsaitlik açılır menüsü GÖRSEL olarak açılmalı' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'B9',
    title: 'Varsayılan e-posta imzasında ham i18n anahtarı',
    area: 'channels',
    route: '/channels/email',
    severity: 'medium',
    status: 'open',
    guard: 'knownBugGuard',
    opened: null,
    lastVerified: '2026-07-28',
    expiry: null,
    repro: ['/channels/email aç', 'imza alanını (textarea/contenteditable) oku'],
    expected: 'Çevrilmiş varsayılan imza metni',
    actual: 'Ham anahtar "channels.emailPage.defaultSignatureText" input değerinde görünüyor',
    technicalEvidence: [],
    possibleCauses: [],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: [],
    evidence: [],
    test: { file: 'tests/known-bugs.authed.spec.js', title: 'B9 · /channels/email · varsayılan imza ham i18n anahtarı göstermemeli' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'B10',
    title: 'Voice üst sekme çubuğu yok (bölüm düzeni kayıp)',
    area: 'voice',
    route: '/voice/regulatory',
    severity: 'medium',
    status: 'open',
    guard: 'knownBugGuard',
    opened: null,
    lastVerified: '2026-07-28',
    expiry: null,
    repro: ['/voice/regulatory aç', 'içerik alanında Voice sekme çubuğunu (Live Calls) ara'],
    expected: 'Voice bölüm sekme çubuğu içerik alanında görünür',
    actual: 'Sekme çubuğu yok → bölüm düzeni kayıp',
    technicalEvidence: [],
    possibleCauses: [],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: [],
    evidence: [],
    test: { file: 'tests/known-bugs.authed.spec.js', title: 'B10 · /voice/regulatory · Voice sekme çubuğu görünmeli (bölüm düzeni)' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'B11',
    title: 'Sesli mesaj işlem butonlarının erişilebilir ismi yok',
    area: 'voice',
    route: '/voice/voicemail',
    severity: 'medium',
    status: 'open',
    guard: 'knownBugGuard',
    opened: null,
    lastVerified: '2026-07-28',
    expiry: null,
    repro: ['/voice/voicemail aç', 'tablo/işlem butonlarının erişilebilir ismini kontrol et (veri gerektirir)'],
    expected: 'Tüm işlem butonlarının erişilebilir ismi var',
    actual: 'İsimsiz işlem butonları (yalnızca sesli mesaj/işlem verisi varsa reproduce olur)',
    technicalEvidence: [],
    possibleCauses: [],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: [],
    evidence: [],
    test: { file: 'tests/known-bugs.authed.spec.js', title: 'B11 · /voice/voicemail · İşlemler butonlarının erişilebilir ismi olmalı' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'B12',
    title: 'TR arayüzde İngilizce/iç metin sızıyor',
    area: 'analytics',
    route: '/analytics',
    severity: 'medium',
    status: 'open',
    guard: 'knownBugGuard',
    opened: null,
    lastVerified: '2026-07-28',
    expiry: null,
    repro: ['/analytics aç (TR arayüz)', 'main metnini oku'],
    expected: 'TR arayüzde İngilizce/iç metin yok',
    actual: 'Deep analytics / Call abandonment / ClickHouse vb. sızıyor (yalnızca TR arayüzde)',
    technicalEvidence: [],
    possibleCauses: [],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: [],
    evidence: [],
    test: { file: 'tests/known-bugs.authed.spec.js', title: 'B12 · /analytics · TR arayüzde İngilizce/iç metin sızmamalı' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'B13',
    title: 'AI sekme etiketinde boşluk eksik ("Yapay ZekaTemsilciler")',
    area: 'ai',
    route: '/ai',
    severity: 'low',
    status: 'open',
    guard: 'knownBugGuard',
    opened: null,
    lastVerified: '2026-07-28',
    expiry: null,
    repro: ['/ai aç (TR arayüz)', 'sekme etiketini oku'],
    expected: 'Sekme etiketinde boşluk doğru ("Yapay Zeka Temsilciler")',
    actual: 'Bitişik yazım "ZekaTemsilciler" (yalnızca TR arayüzde)',
    technicalEvidence: [],
    possibleCauses: [],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: [],
    evidence: [],
    test: { file: 'tests/known-bugs.authed.spec.js', title: 'B13 · /ai · sekme etiketinde boşluk eksik olmamalı ("Yapay ZekaTemsilciler")' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'B14',
    title: 'Reddedilen DID talebinin nedeni tam okunamıyor',
    area: 'voice',
    route: '/voice/dids',
    severity: 'medium',
    status: 'open',
    guard: 'knownBugGuard',
    opened: null,
    lastVerified: '2026-07-28',
    expiry: null,
    repro: ['/voice/dids aç', 'Bekleyen Talepler → reddedilmiş talebin nedenini incele (veri gerektirir)'],
    expected: 'Red nedeni tam okunabilir (tooltip/title ile)',
    actual: 'Red nedeni kırpık; tooltip/title yok (yalnızca reddedilmiş talep varsa reproduce olur)',
    technicalEvidence: [],
    possibleCauses: [],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: [],
    evidence: [],
    test: { file: 'tests/known-bugs.authed.spec.js', title: 'B14 · /voice/dids · reddedilen talebin nedeni tam okunabilir olmalı' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'B15',
    title: 'Sol menü bölüm üst-başlığı bölüm köküne gitmiyor',
    area: 'navigation',
    route: '/ai',
    severity: 'medium',
    status: 'open',
    guard: 'knownBugGuard',
    opened: null,
    lastVerified: '2026-07-28',
    expiry: null,
    repro: ['/ai/voice aç', 'sol menüde "AI/Yapay Zeka" üst-başlığına tıkla', 'URL yolunu kontrol et'],
    expected: 'Üst-başlık bölüm köküne (/ai) gider',
    actual: 'URL değişmiyor (grup başlığı yalnız alt-menü açıyor) — UX beklentisi',
    technicalEvidence: [],
    possibleCauses: [],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: [],
    evidence: [],
    test: { file: 'tests/known-bugs.authed.spec.js', title: 'B15 · Sol menü · bölüm üst-başlığı bölüm köküne gitmeli' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'ANALYTICS-A',
    title: '"Deep analytics" bölümü hiçbir dilde çevrilmiyor',
    area: 'analytics',
    route: '/analytics',
    severity: 'medium',
    status: 'open',
    guard: 'knownBugGuard',
    opened: null,
    lastVerified: null,
    expiry: null,
    repro: ['/analytics aç', 'dili tr/fr/ar yap', 'Deep analytics bölümü metnini oku'],
    expected: 'Deep analytics başlıkları hedef dilde çevrili',
    actual: 'Çevrilmemiş İngilizce metin sızıyor (tr/fr/ar). B12 yalnız TR; bu guard üç dili kapsar',
    technicalEvidence: [],
    possibleCauses: [],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: [],
    evidence: [],
    test: { file: 'tests/analytics.authed.spec.js', title: 'BULGU A [tr]: "Deep analytics" bölümü tr arayüzde çevrili olmalı' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'ANALYTICS-B',
    title: 'İç/teknik terim "ClickHouse" kullanıcıya görünüyor',
    area: 'analytics',
    route: '/analytics',
    severity: 'medium',
    status: 'open',
    guard: 'knownBugGuard',
    opened: null,
    lastVerified: null,
    expiry: null,
    repro: ['/analytics aç', 'main metnini oku'],
    expected: 'İç/teknik terim kullanıcıya görünmez',
    actual: 'Kullanıcıya dönük metinde "ClickHouse" görünüyor (İngilizce dahil)',
    technicalEvidence: [],
    possibleCauses: [],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: [],
    evidence: [],
    test: { file: 'tests/analytics.authed.spec.js', title: 'BULGU B: iç terim "ClickHouse" kullanıcıya görünmemeli' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'REPORTS-INTL',
    title: 'AI Insights intl FORMATTING_ERROR (sessiz konsol hatası)',
    area: 'reports',
    route: '/reports',
    severity: 'medium',
    status: 'open',
    guard: 'knownBugGuard',
    opened: null,
    lastVerified: null,
    expiry: null,
    repro: ['/reports aç', 'AI Insights sekmesine tıkla', 'konsol/diagnostics temizliğini kontrol et'],
    expected: 'Sessiz intl hatası yok',
    actual: "intl FORMATTING_ERROR (\"variable 'type' was not provided to the string 'Generate AI insights...'\")",
    technicalEvidence: [],
    possibleCauses: ['Eksik intl değişkeni ("type") — çeviri string\'ine sağlanmamış (konsol mesajında belirtilmiş)'],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: [],
    evidence: [],
    test: { file: 'tests/reports.authed.spec.js', title: 'sayfa intl FORMATTING_ERROR sessiz hatası üretmemeli @known-bug' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'REPORTS-AIKEY',
    title: 'AI Insights panelinde ham i18n anahtarı (reports.aiInsightsDesc)',
    area: 'reports',
    route: '/reports',
    severity: 'medium',
    status: 'open',
    guard: 'knownBugGuard',
    opened: null,
    lastVerified: null,
    expiry: null,
    repro: ['/reports aç', 'AI Insights sekmesine tıkla', 'panel metnini oku'],
    expected: 'Çevrilmiş açıklama',
    actual: 'Ham anahtar "reports.aiInsightsDesc" görünüyor',
    technicalEvidence: [],
    possibleCauses: [],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: [],
    evidence: [],
    test: { file: 'tests/reports.authed.spec.js', title: 'AI Insights panelinde ham i18n anahtarı sızmamalı (reports.aiInsightsDesc) @known-bug' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'REPORTS-SECTIONS-TZ',
    title: 'Date Range "Today" etiketi UTC (yerel değil)',
    area: 'reports',
    route: '/reports/call',
    severity: 'medium',
    status: 'open',
    guard: 'knownBugGuard',
    opened: null,
    lastVerified: null,
    expiry: null,
    repro: ['/reports/call aç (Europe/Istanbul)', '"Today" preset seç', 'Date Range başlangıç etiketini oku'],
    expected: 'Etiket yerel bugünü gösterir',
    actual: 'Etiket UTC ile basılıyor → UTC+3\'te başlangıç bir gün geride ("dün") görünüyor',
    technicalEvidence: [],
    possibleCauses: ['Aralık API\'de yerel-gece-yarısına göre doğru; etiket UTC ile formatlanıyor (manuel raporda belgelenmiş)'],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: [],
    evidence: [{ path: 'docs/manuel-test-raporu/02-tarih-araligi-utc.md', source: 'manual-report', piiReviewed: true }],
    test: { file: 'tests/reports-sections.authed.spec.js', title: 'L3: "Today" preset tarih etiketi YEREL bugünü göstermeli (UTC değil) [BULGU]' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'DASHBOARDS-SHARE-OVERFLOW',
    title: 'Paylaş diyaloğu yatayda taşıyor (~266px)',
    area: 'reports',
    route: '/reports/dashboards',
    severity: 'medium',
    status: 'open',
    guard: 'knownBugGuard',
    opened: null,
    lastVerified: null,
    expiry: null,
    repro: ['/reports/dashboards aç', 'paylaş diyaloğunu aç (her dilde)', 'yatay taşmayı ölç'],
    expected: 'Diyalog içeriği kart içinde kalır (taşma ≤ 2px)',
    actual: 'Uzun URL diyaloğu ~266px taşırıyor',
    technicalEvidence: [],
    possibleCauses: ['flex-1 kapsayıcıda min-w-0 yok (kaynakta gözlenen)'],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: ['flex kapsayıcıya min-w-0 ekle'],
    evidence: [{ path: 'docs/manuel-test-raporu/01-panolar-paylas-tasma.md', source: 'manual-report', piiReviewed: true }],
    test: { file: 'tests/reports-dashboards.authed.spec.js', title: 'L3 görev OK: [en] paylaş diyaloğu yatayda taşmamalı [BULGU 1] @layout @known-bug' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'CAMPAIGNS-PAGER',
    title: '10+ kampanyada sayfalama/daha-fazla kontrolü yok',
    area: 'campaigns',
    route: '/campaigns/outbound',
    severity: 'medium',
    status: 'open',
    guard: 'knownBugGuard',
    opened: null,
    lastVerified: null,
    expiry: null,
    repro: ['/campaigns/outbound aç', 'liste yanıtında hasNextPage:true ise sayfalama/satır sayısını kontrol et'],
    expected: 'Kalan kampanyalara erişim (pager veya 10+ satır)',
    actual: 'Liste 10\'da kapanıyor; API hasNextPage:true ama sayfalama/sonsuz-kaydırma yok (10+ kampanya varsa)',
    technicalEvidence: [],
    possibleCauses: [],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: [],
    evidence: [],
    test: { file: 'tests/campaigns-outbound.authed.spec.js', title: 'BULGU 1: 10+ kampanya varsa sayfalama/daha-fazla kontrolü olmalı' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'CAMPAIGNS-ICON-A11Y',
    title: 'Satır işlem ikonları (göz/sil) erişilebilir isimsiz',
    area: 'campaigns',
    route: '/campaigns/outbound',
    severity: 'medium',
    status: 'open',
    guard: 'knownBugGuard',
    opened: null,
    lastVerified: null,
    expiry: null,
    repro: ['/campaigns/outbound aç', 'satır işlem ikonlarının erişilebilir ismini kontrol et'],
    expected: 'göz/sil ikonlarının erişilebilir ismi var',
    actual: 'Satır işlem ikonları erişilebilir isimsiz (a11y button-name)',
    technicalEvidence: [],
    possibleCauses: [],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: [],
    evidence: [],
    test: { file: 'tests/campaigns-outbound.authed.spec.js', title: 'BULGU 2: satır işlem ikonlarının (göz/sil) erişilebilir ismi olmalı' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'AGENTS-TZ',
    title: '"Last refreshed" saati UTC (yerel değil)',
    area: 'supervisor',
    route: '/supervisor/agents',
    severity: 'medium',
    status: 'open',
    guard: 'knownBugGuard',
    opened: null,
    lastVerified: null,
    expiry: null,
    repro: ['/supervisor/agents aç (Europe/Istanbul)', '"Last refreshed at HH:MM" saatini oku'],
    expected: 'Yerel saat gösterilir',
    actual: 'Sunucu UTC saatini çevirmeden basıyor → UTC+3\'te ~180 dk sapma (Wallboard BULGU 4 ile aynı)',
    technicalEvidence: [],
    possibleCauses: ['Sunucu UTC zamanı yerel zamana çevrilmeden bastırılıyor (kaynakta gözlenen)'],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: [],
    evidence: [],
    test: { file: 'tests/supervisor-agents.authed.spec.js', title: 'BULGU: "Last refreshed" saati yerel saat olmalı (UTC değil)' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'WALLBOARD-I18N',
    title: '"Refresh All"/"Auto-scroll" hiçbir dilde çevrilmiyor',
    area: 'supervisor',
    route: '/supervisor/wallboard',
    severity: 'medium',
    status: 'open',
    guard: 'knownBugGuard',
    opened: null,
    lastVerified: null,
    expiry: null,
    repro: ['/supervisor/wallboard aç', 'dili TR yap', '"Refresh All"/"Auto-scroll" butonlarını ara'],
    expected: 'Butonlar TR arayüzde çevrili',
    actual: '"Refresh All"/"Auto-scroll" çevrilmiyor (İngilizce kalıyor)',
    technicalEvidence: [],
    possibleCauses: [],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: [],
    evidence: [],
    test: { file: 'tests/supervisor-wallboard.authed.spec.js', title: 'BULGU 2: "Refresh All"/"Auto-scroll" Türkçe arayüzde çevrilmeli' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'CONTACTS-F1',
    title: 'Satır ara butonu erişilebilir ismi ham anahtar "callContact"',
    area: 'contacts',
    route: '/contacts',
    severity: 'medium',
    status: 'open',
    guard: 'knownBugGuard',
    opened: null,
    lastVerified: '2026-07-28',
    expiry: null,
    repro: ['/contacts aç', 'satır ara butonunun aria-label\'ını oku'],
    expected: 'aria-label anlamlı (ham anahtar değil)',
    actual: 'aria-label ham i18n anahtarı "callContact"',
    technicalEvidence: [],
    possibleCauses: [],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: [],
    evidence: [],
    test: { file: 'tests/contacts.authed.spec.js', title: 'BULGU F1: satır ara butonu erişilebilir ismi ham anahtar "callContact" olmamalı' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'CONTACTS-F2',
    title: 'Kişi detayı sil butonu ham anahtar "contacts.delete" gösteriyor',
    area: 'contacts',
    route: '/contacts',
    severity: 'medium',
    status: 'open',
    guard: 'knownBugGuard',
    opened: null,
    lastVerified: '2026-07-28',
    expiry: null,
    repro: ['/contacts aç', 'ilk kişiyi aç', 'Quick Actions render olsun', 'sil butonu metnini kontrol et'],
    expected: 'Çevrilmiş "Delete/Sil" metni',
    actual: 'Görünür metin ham anahtar "contacts.delete"',
    technicalEvidence: [],
    possibleCauses: [],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: [],
    evidence: [],
    test: { file: 'tests/contacts.authed.spec.js', title: 'BULGU F2: kişi detayı sil butonu ham anahtar "contacts.delete" göstermemeli' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'WALLBOARD-THEME',
    title: 'Tema seçici "Dark" seçilince koyu tema uygulanmıyor',
    area: 'supervisor',
    route: '/supervisor/wallboard',
    severity: 'medium',
    status: 'open',
    guard: 'knownBugGuard',
    opened: null,
    lastVerified: null,
    expiry: null,
    repro: ['/supervisor/wallboard aç', 'Tema seçici → "Dark"', '<html> class\'ını kontrol et'],
    expected: '<html> koyu temaya geçer (dark class)',
    actual: 'Seçici değeri "Dark" olsa da <html> class "light" kalıyor (tema uygulanmıyor)',
    technicalEvidence: [],
    possibleCauses: [],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: [],
    evidence: [],
    test: { file: 'tests/supervisor-wallboard.authed.spec.js', title: 'L3 görev OK: "Dark" seçilince koyu tema uygulanmalı [BULGU 1]' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'WALLBOARD-AUTOSCROLL',
    title: 'Auto-scroll toggle açılıyor ama içerik kaydırmıyor',
    area: 'supervisor',
    route: '/supervisor/wallboard',
    severity: 'medium',
    status: 'open',
    guard: 'knownBugGuard',
    opened: null,
    lastVerified: null,
    expiry: null,
    repro: ['/supervisor/wallboard aç', 'içerik taşacak viewport ayarla', 'Auto-scroll toggle aç', 'scrollTop değişimini gözle'],
    expected: 'İçerik taşınca otomatik kaydırır (maxScrollTop > 0)',
    actual: 'Toggle aktif duruma geçiyor ama (TV modu dahil) hiç kaydırmıyor',
    technicalEvidence: [],
    possibleCauses: [],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: [],
    evidence: [],
    test: { file: 'tests/supervisor-wallboard.authed.spec.js', title: 'L3 görev OK: içerik taşınca otomatik kaydırmalı [BULGU 3]' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'WALLBOARD-LIVE-TZ',
    title: 'Live son-güncelleme saati UTC (yerel değil)',
    area: 'supervisor',
    route: '/supervisor/wallboard',
    severity: 'medium',
    status: 'open',
    guard: 'knownBugGuard',
    opened: null,
    lastVerified: null,
    expiry: null,
    repro: ['/supervisor/wallboard aç (Europe/Istanbul)', 'Live son-güncelleme saatini oku'],
    expected: 'Yerel saat gösterilir',
    actual: 'Saat UTC basılıyor → UTC+3\'te ~180 dk sapma (AGENTS-TZ ile aynı sınıf)',
    technicalEvidence: [],
    possibleCauses: ['Sunucu UTC zamanı yerel zamana çevrilmeden bastırılıyor (kaynakta gözlenen)'],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: [],
    evidence: [],
    test: { file: 'tests/supervisor-wallboard.authed.spec.js', title: 'L3 görev OK: gösterilen son-güncelleme saati yerel saat olmalı (UTC değil) [BULGU 4]' },
    owner: null,
    issueRef: null,
  },
  {
    id: 'WALLBOARD-RESUME-I18N',
    title: '"Resume queue" menü öğesi hiçbir dilde çevrilmiyor',
    area: 'supervisor',
    route: '/supervisor/wallboard',
    severity: 'low',
    status: 'open',
    guard: 'knownBugGuard',
    opened: null,
    lastVerified: null,
    expiry: null,
    repro: ['/supervisor/wallboard aç', 'dili TR yap', '⋮ kuyruk menüsünü aç', '"Resume queue" öğesini kontrol et'],
    expected: 'TR menüde çevrili (diğer 4 öğe gibi)',
    actual: 'İngilizce "Resume queue" kalıyor (menü içi çeviri sızıntısı)',
    technicalEvidence: [],
    possibleCauses: [],
    rootCauseCandidate: null,
    rootCause: null,
    suggestedFixes: [],
    evidence: [],
    test: { file: 'tests/supervisor-wallboard.authed.spec.js', title: 'BULGU 5: "Resume queue" Türkçe menüde çevrilmeli' },
    owner: null,
    issueRef: null,
  },
]);
